project_id = "mufevyjzslfskdzccoao"

[functions.chat]
verify_jwt = false

[functions.line-webhook]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = true

[functions.test-line-connection]
verify_jwt = true

[functions.test-facebook-connection]
verify_jwt = true

[functions.settings-crypto]
verify_jwt = true

[functions.send-broadcast]
verify_jwt = true

[functions.process-scheduled-broadcasts]
verify_jwt = false

[functions.analyze-payment-slip]
verify_jwt = true

[functions.scrape-website]
verify_jwt = true

[functions.process-scheduled-scrapes]
verify_jwt = false

[functions.process-knowledge-file]
verify_jwt = true

[functions.auto-notify-order]
verify_jwt = false

[functions.update-customer-names]
verify_jwt = true

[functions.log-error]
verify_jwt = false

[functions.generate-product-faq]
verify_jwt = true
