project_id = "mufevyjzslfskdzccoao"

[functions.chat]
verify_jwt = false

[functions.line-webhook]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.test-line-connection]
verify_jwt = false

[functions.test-facebook-connection]
verify_jwt = false
